[tool.isort]
force_single_line = true
profile = "black"
skip = [
	".bzr",
	".direnv",
	".eggs",
	".git",
	".hg",
	".mypy_cache",
	".nox",
	".pants.d",
	".svn",
	".tox",
	".venv",
	"_build",
	"buck-out",
	"build",
	"dist",
	"node_modules",
	"venv",
	"alembic/versions",
]

[tool.vulture]
exclude = [
	".venv",
	".git",
	"__pycache__",
	".mypy_cache",
	".pytest_cache",
	"alembic/versions",
	"static",
]
min_confidence = 100

[tool.black]
extend_exclude = "alembic/versions"

[tool.pytest.ini_options]
asyncio_mode = "auto"
