version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7.10
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pytest 
          name: Test
      - run:
          command: mypy .
          name: mypy
      - run:
          command: black . --check
          name: black --check

workflows:
  main:
    jobs:
      - build-and-test
