version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  lint:
    executor:
      name: python/default
      tag: 3.7.10
    parameters:
      lint-tool:
        type: string
    steps:
      - checkout
      - python/install-packages
      - run: << parameters.lint-tool >>

workflows:
  main:
    jobs:
      - python/test:
          test-tool: pytest
          version: 3.7.10
      - lint:
          lint-tool: mypy .
      - lint:
          lint-tool: black . --check
      - lint:
          lint-tool: isort . --check
      - lint:
          lint-tool: flake8
      - lint:
          lint-tool: vulture .
