version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  lint:
    executor:
      name: python/default
      tag: 3.7.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: make lint
  test:
    docker:
      - image: cimg/python:3.7.10
        environment:
          DATABASE_URL: postgres://fanviddb:fanviddb_test@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:12.6
        environment:
          POSTGRES_USER: fanviddb_test
          POSTGRES_PASSWORD: fanviddb_test
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: run tests
          command: |
            mkdir test-results
            pytest --junitxml=test-results/report.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - test
      - lint
