"""added api key table

Revision ID: 57145519c714
Revises: a0df077b8f2c
Create Date: 2021-03-18 07:37:01.612148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57145519c714'
down_revision = 'a0df077b8f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
