"""empty message

Revision ID: 5b227dc4ca2f
Revises: ec688d54f6cb
Create Date: 2021-05-02 13:49:07.847290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b227dc4ca2f"
down_revision = "ec688d54f6cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    fanvids = sa.table("fanvids", sa.column("audio_language", sa.String))
    op.execute(
        fanvids.update()
        .where(fanvids.c.audio_language == "en-US")
        .values({"audio_language": '["en-US"]'})
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
