"""marked additional JSON fields

Revision ID: a0df077b8f2c
Revises: c5cef61ec67a
Create Date: 2021-03-14 20:01:24.329480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0df077b8f2c'
down_revision = 'c5cef61ec67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
