"""rename audio language -> languages

Revision ID: a98187169b2b
Revises: 5b227dc4ca2f
Create Date: 2021-05-02 13:54:48.339292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98187169b2b'
down_revision = '5b227dc4ca2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fanvids', 'audio_language', new_column_name='audio_languages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fanvids', 'audio_languages', new_column_name='audio_languages')
    # ### end Alembic commands ###
