"""marked fanvid db fields as non-nullable

Revision ID: ec688d54f6cb
Revises: b3dd7f120910
Create Date: 2021-05-01 17:50:09.352014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec688d54f6cb'
down_revision = 'b3dd7f120910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fanvids', 'audio_artists_or_sources',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'audio_language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'audio_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'content_notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'created_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('fanvids', 'creators',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('fanvids', 'fandoms',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'length',
               existing_type=postgresql.INTERVAL(),
               nullable=False)
    op.alter_column('fanvids', 'modified_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('fanvids', 'premiere_event',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'thumbnail_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'unique_identifiers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fanvids', 'urls',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fanvids', 'urls',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'unique_identifiers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'thumbnail_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'premiere_event',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'modified_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('fanvids', 'length',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    op.alter_column('fanvids', 'fandoms',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'creators',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('fanvids', 'created_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('fanvids', 'content_notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'audio_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'audio_language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fanvids', 'audio_artists_or_sources',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
