"""added api key table

Revision ID: efc64168fb33
Revises: 57145519c714
Create Date: 2021-03-20 10:15:01.894324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc64168fb33'
down_revision = '57145519c714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('pk', sa.String(), nullable=False),
    sa.Column('hashed_api_key', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    # ### end Alembic commands ###
