import re

VIDEO_EXTENSIONS = frozenset(
    (
        ".3g2",
        ".3gp",
        ".asf",
        ".asx",
        ".avc",
        ".avi",
        ".avs",
        ".bivx",
        ".bup",
        ".divx",
        ".dv",
        ".dvr-ms",
        ".evo",
        ".fli",
        ".flv",
        ".m2t",
        ".m2ts",
        ".m2v",
        ".m4v",
        ".mkv",
        ".mov",
        ".mp4",
        ".mpeg",
        ".mpg",
        ".mts",
        ".nsv",
        ".nuv",
        ".ogm",
        ".ogv",
        ".tp",
        ".pva",
        ".qt",
        ".rm",
        ".rmvb",
        ".sdp",
        ".svq3",
        ".strm",
        ".ts",
        ".ty",
        ".vdr",
        ".viv",
        ".vob",
        ".vp3",
        ".wmv",
        ".wpl",
        ".wtv",
        ".xsp",
        ".xvid",
        ".webm",
    )
)

FILENAME_PUNCTUATION_RE = re.compile(r"[\W_]+")
