title: FanvidDB
description: >- # this means to ignore newlines until "baseurl:"
  A central repository for fanvid-related metadata, useful for Plex or any other purpose.
baseurl: ""
url: "https://docs.fanviddb.com"

github:
  repository_url: https://github.com/FanvidDB/fanviddb-server

# Build settings
theme: jekyll-theme-minimal
markdown: CommonMark
